# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
#
# Monitors
monitor = , preferred, auto, 1.5

# Workspaces
workspace = special:passwords
workspace = special:music
workspace = special:scratchpad
workspace = special:signal
# workspace = special:passwords, monitor:HDMI-A-1
# workspace = special:music, monitor:HDMI-A-1
# workspace = special:scratchpad, monitor:HDMI-A-1
# workspace = special:signal, monitor:HDMI-A-1

# Window Rules
windowrulev2 = workspace 3, class:^(brave-x.com__-Default)$
windowrulev2 = workspace 3, class:^(brave-grok.com__-Default)$
windowrulev2 = workspace 9, class:^(brave-mail.proton.me__u_0_inbox-Default)$
windowrulev2 = workspace 9, class:^(brave-outlook.live.com__mail_0_-Default)$
windowrulev2 = workspace 9, class:^(brave-www.icloud.com__mail_-Default)$
windowrulev2 = workspace special:passwords, class:^(Proton Pass)$
windowrulev2 = float, class:^(Proton Pass)$
windowrulev2 = size 1800 1200, class:^(Proton Pass)$
windowrulev2 = center, class:^(Proton Pass)$
# windowrulev2 = move 350 125, class:^(Proton Pass)$  # Optional: Prevent off-screen on high-res monitor
windowrulev2 = workspace special:music, class:^(Spotify)$
windowrulev2 = float, class:^(Spotify)$
windowrulev2 = size 1800 1200, class:^(Spotify)$
windowrulev2 = center, class:^(Spotify)$
# windowrulev2 = move 350 125, class:^(Spotify)$  # Optional: Prevent off-screen
windowrulev2 = workspace special:scratchpad, class:^(Alacritty)$
windowrulev2 = float, class:^(Alacritty)$
windowrulev2 = size 1200 800, class:^(Alacritty)$
windowrulev2 = center, class:^(Alacritty)$
windowrulev2 = workspace special:signal, class:^(Signal)$
windowrulev2 = float, class:^(signal)$
windowrulev2 = size 1800 1200, class:^(signal)$
windowrulev2 = center, class:^(signal)$
# windowrulev2 = move 350 125, class:^(signal)$
